### ISSUE TITLE
Does this work when the target is static ?

### ISSUE THREAD

**Issue by kissu** [potato4d/nuxt-basic-auth-module#158]
So yeah, basically this module is working great while `nuxt dev`.

But when `nuxt generate` then `nuxt start`, so it's giving me
```bash
Environment: production
Rendering: server-side
Target: static
```

It just ignore the whole security even with `enabled: true`.

Wanted to be sure what is happening there. 😄

**Comment by zeitchef** [comment]
I'd love to know about this as well!

**Comment by tallcoder** [comment]
Good question! Would love to know myself.

**Comment by potato4d** [comment]
@tallcoder 
Nuxt.js's static mode works as a static website.
In a static website, Nuxt.js only serves files and does not allow Node.js-derived functionality to operate.
Therefore, the nuxt-basic-auth-module, which relies on Nuxt.js, does not work in static, which is the correct behavior.
