### ISSUE TITLE
"undefined" as enabled option doesn't skip module registration

### ISSUE THREAD

**Issue by krisimmig** [potato4d/nuxt-basic-auth-module#202]
When giving the "enabled" option "undefined" as value, for example when using ENV variables that are not present on all environments, the module is still activated.

I would propose to change this so that "undefined" also skips the registration. Thoughts? I can make a pull request if this sounds good to everyone.

**Comment by potato4d** [comment]
I think that's a great suggestion!

**Comment by krisimmig** [comment]
Ok, I will do this now.
