### ISSUE TITLE
Router support

### ISSUE THREAD

**Issue by antfu** [potato4d/nuxt-basic-auth-module#32]
In my case, I have a demand to auth some paths like `/admin`.

Could we have a field in config to specific which routes should be managed by this module?

Something like this:
```js
module.exports = {
  modules: [
    'nuxt-basic-auth-module'
  ],
  basic: {
    name: 'AUTH USER NAME HERE',
    pass: 'AUTH PASSWORD HERE',
    match(route) {
        // return true to enable basic auth
        return route.path.startsWith('/admin')
    },
  },
  // ...
}
```

**Comment by potato4d** [comment]
@antfu 

thank you for the request.
I'm wondering if I could do that with a regular expression literal or with a function.

Or it may be good with both, but I have not made a decision yet.

If you have a good idea or implementation, I would like a comment.

**Comment by antfu** [comment]
In my opinion, supporting both is a good option. Coz function always adds more flexibility while regular expressions are simpler.

Would love to make a PR later.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by potato4d** [comment]
resolved.
thanks @antfu

**Comment by potato4d** [comment]
@antfu 
released!
https://www.npmjs.com/package/nuxt-basic-auth-module/v/1.2.0
